# Generated by Django 4.2.5 on 2023-09-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologie', '0001_initial'),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_required', models.CharField(blank=True, max_length=100, null=True)),
                ('education_required', models.CharField(blank=True, max_length=100, null=True)),
                ('languages_required', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('active', 'Activer'), ('closed', 'Fermer'), ('pending', 'attend')], default='active', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.profilentreprise')),
                ('technologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologie.technologie')),
            ],
        ),
    ]
