# Generated by Django 4.2.5 on 2023-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='cv/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
